services:
  front:
    image: transcode-front:local
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
      APP_RUNTIME_MODE: "backend"
      APP_BACKEND_BASE_URL: "https://trapi.demeter-sante.fr/api/v1"
